config/routes.rb
Rails.application.routes.draw do

  root 'object_models#index'
  
  resources :items, only: [:index, :show]
  resources :object_models, only: [:index, :show] do
    resources :items, only: [:index]
  end
  
end

app/models/item.rb
# An object id is used to store object ids gathered from the fedora 3 instance
class Item < ActiveRecord::Base
  
  belongs_to :object_model
  delegate :name, to: :object_model, prefix: true
  
  has_many :properties, through: :object_model
  has_many :property_values
  has_many :object_properties
  
  serialize :external_datastreams, Array
  
  paginates_per 25
  
  def self.populate(hash)
    return unless hash['results']
    hash['results'].each do |result|
      text = result['subject']
      match = text.match uuid_pattern
      find_or_create_by(identifier: match[0]) if match
    end
  end
  
  def self.uuid_pattern
    prefix = 'uuid'
    separator = '\:'
    uuid_pattern = '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}'
    Regexp.new (prefix + separator + uuid_pattern)
  end
  
  def to_param
    identifier
  end
  
end

app/models/object_id.rb
# An object id is used to store object ids gathered from the fedora 3 instance
class ObjectId < ActiveRecord::Base
  
  def self.populate(hash)
    return unless hash['results']
    hash['results'].each do |result|
      text = result['subject']
      match = text.match uuid_pattern
      find_or_create_by(identifier: match[0]) if match
    end
  end
  
  def self.uuid_pattern
    prefix = 'uuid'
    separator = '\:'
    uuid_pattern = '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}'
    Regexp.new (prefix + separator + uuid_pattern)
  end
  
end

app/models/object_model.rb
class ObjectModel < ActiveRecord::Base
  
  UNKNOWN = 'unknown'
  MANY_THREASHOLD = 10
  MULTIPLE = 'multiple'
  UNIQUE = 'unique'
  
  has_many :items
  has_many :properties
  has_many :object_properties, through: :items
  
  def object_property_usage
    object_properties.group(:name).count
  end
  
  def object_property_values_for(name)
    object_properties.where(name: name).pluck(:value)
  end
  
  # A hash with object property names as keys and values as the values
  # used by for those names. 
  # If there are many values (see MANY_THREASHOLD) then two options
  # will be returned:
  # 
  #   MULTIPLE: there are many difference values used for this object property
  #   UNIQUE:   each object_property of this type has a unique value
  #
  def object_property_usage_report
    object_property_usage.inject({}) do |hash, key_value|
      name, count = key_value
      values = object_property_values_for(name).uniq.sort
      hash[name] = if values.length > MANY_THREASHOLD
        values.length == count ? UNIQUE : MULTIPLE
      else
        values
      end
      hash
    end
  end
  
end

app/models/object_property.rb
class ObjectProperty < ActiveRecord::Base
  belongs_to :item
  
  def short_name
    name.split('#').last if name?
  end
  
  def property_type
    external? ? :extproperty : :property
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :object_model
  
  def multiple?
    multiple_type
  end
  
end

app/models/property_value.rb
class PropertyValue < ActiveRecord::Base
  
  belongs_to :item
  
  scope :namespace, ->(name){ where(namespace: name) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    @items = object_model ? object_model.items : Item.all
    @items = @items.order(:identifier).page params[:page]
  end

  def show
    @item = Item.find_by(identifier: params[:id])
  end
  
  private
  def object_model
    return unless params[:object_model_id]
    @object_model ||= ObjectModel.find(params[:object_model_id])
  end
  
end

app/controllers/object_models_controller.rb
class ObjectModelsController < ApplicationController
  def index
    @object_models = ObjectModel.all
  end

  def show
    @object_model = ObjectModel.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def active_if_index_for?(name)
    'active' if current_page?(controller: name, action: 'index')
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/object_models_helper.rb
module ObjectModelsHelper
end

app/views/items/index.html.erb
<h1>Items<%= ": #{@object_model.name}" if @object_model %></h1>
<ul class="list-unstyled">
<% @items.each do |item| %>
  <li><%= link_to item.identifier, item %></li>
<% end %>
</ul>

<%= paginate @items %>

app/views/items/show.html.erb
<h1>Item: <%= @item.identifier %></h1>

<%= link_to('Data source', @item.source_url, class: 'btn btn-info') if @item.source_url? %>

<h2>Object Type</h2>
<p class="lead">
  <%= link_to @item.object_model_name, @item.object_model %>
</p>

<h2>Object Properties</h2>
<table class="table">
  <tr>
    <th>Type</th>
    <th>Name</th>
    <th>Value</th>
    <th>Full name</th>
  </tr>
<% @item.object_properties.each do |object_properties| %>
  <tr>
    <td><%= object_properties.property_type %></td>
    <td><%= object_properties.short_name %></td>
    <td><%= object_properties.value %></td>
    <td><%= object_properties.name %></td>
  </tr>
<% end %>
</table>

<% @item.property_values.group_by(&:datastream).each do |datastream, property_values| %>
<h2>Datastream: <%= datastream  %></h2>
<table class="table">
  <tr>
    <th>Namespace:Name</th>
    <th>Value<th>
  </tr>
<%   property_values.each do |property_value| %>
  <tr>
    <td>
      <%= property_value.namespace %>:<%= property_value.name %>
    </td>
    <td><%= property_value.value %></td>
  </tr>
<%   end %>
</table>
<% end %>

<h2>External Datastreams</h2>
<p>This item also has data stored in the following external datastreams:</p>
<ul>
<% @item.external_datastreams.each do |external_datastream| %>
  <li><%= external_datastream %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>MigrateFedora3To4</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li role="presentation" class="<%= active_if_index_for? 'object_models' %>">
        <%= link_to 'Object Models', root_path %>
      </li>
      <li role="presentation" class="<%= active_if_index_for? 'items' %>">
        <%= link_to 'Items', items_path %>
      </li>
    </ul>
    
    <%= yield %>
  </div>

</body>
</html>

app/views/object_models/index.html.erb
<h1>ObjectModels</h1>
<ul>
<% @object_models.each do |object_model| %>
  <li><%= link_to object_model.name, object_model %></li>
<% end %>
</ul>

app/views/object_models/show.html.erb
<h1>Object Model: <%= @object_model.name %></h1>
<p>
  <%= pluralize(@object_model.items.count, 'item is', 'items are') %>
  associated with this Object Model.
</p>
<%= 
  link_to 'Associated items', object_model_items_path(@object_model), class: 'btn btn-info' 
%>

<h2>Object properties</h2>
<table class="table">
  <tr><th>Name</th><th>Values used</th></tr>
<% @object_model.object_property_usage_report.each do |name, values| %>
  <tr>
    <td><%= name %></td>
    <td><%= values %></td>
  </tr>
<% end %>
</table>

<% @object_model.properties.group_by(&:datastream).each do |datastream, properties| %>
<h2>Datastream: <%= datastream %></h2>
<%   properties.each do |property| %>
<p>
  property :<%= property.name %>, 
  predicate: ::RDF::<%= property.namespace.try(:upcase) %>.<%= property.name %>, 
  multiple: <%= property.multiple? %>
</p>
<%   end %>
<% end %>